"""Python helpers for EMC Locus laboratory automation."""

from .gui_actions import (
    advance_project_stage,
    attach_metrology_document,
    complete_contract_review_item_action,
    create_project_record,
    create_test_category,
    next_project_stage,
    register_metrology_instrument,
    record_metrology_calibration,
    record_dataset_retention_action,
    record_update_install_action,
    record_update_validation_action,
    refresh_bootstrap,
    run_simulated_emc_test_action,
    schedule_service_item,
    set_metrology_instrument_capabilities,
    set_metrology_instrument_availability,
    set_metrology_instrument_serviceability,
)
from .gui_bootstrap import build_bootstrap, build_fixture_bootstrap, write_bootstrap_js
from .local_agent_client import LocalAgentClient, LocalAgentError, generate_operation_id
from .migrations import Migration, discover_migrations, validate_sqlite_migrations
from .qt_console_data import build_console_bootstrap_from_repositories
from .qt_console_models import (
    ConsoleViewModel,
    FormFieldSpec,
    OperatorActionIntent,
    OperatorFormSpec,
    StatusMetric,
    TableViewModel,
    build_console_view_model,
    build_operator_form_specs,
)
from .session_plan import SessionPlan, Workstream, default_backlog
from .sqlite_repositories import (
    MeasurementDataRepository,
    MetrologyRepository,
    ProjectRepository,
    SQLiteDomainRepository,
    SyncRepository,
    TestDefinitionRepository,
    UpdateCatalogRepository,
)

__all__ = [
    "Migration",
    "MeasurementDataRepository",
    "MetrologyRepository",
    "ProjectRepository",
    "SessionPlan",
    "SQLiteDomainRepository",
    "SyncRepository",
    "ConsoleViewModel",
    "FormFieldSpec",
    "LocalAgentClient",
    "LocalAgentError",
    "OperatorActionIntent",
    "OperatorFormSpec",
    "StatusMetric",
    "TableViewModel",
    "TestDefinitionRepository",
    "UpdateCatalogRepository",
    "Workstream",
    "advance_project_stage",
    "attach_metrology_document",
    "build_bootstrap",
    "build_console_bootstrap_from_repositories",
    "build_console_view_model",
    "build_fixture_bootstrap",
    "build_operator_form_specs",
    "complete_contract_review_item_action",
    "create_project_record",
    "create_test_category",
    "discover_migrations",
    "default_backlog",
    "generate_operation_id",
    "next_project_stage",
    "register_metrology_instrument",
    "record_metrology_calibration",
    "record_dataset_retention_action",
    "record_update_install_action",
    "record_update_validation_action",
    "refresh_bootstrap",
    "run_simulated_emc_test_action",
    "schedule_service_item",
    "set_metrology_instrument_capabilities",
    "set_metrology_instrument_availability",
    "set_metrology_instrument_serviceability",
    "validate_sqlite_migrations",
    "write_bootstrap_js",
]
