use crate::{identifiers::ProjectCode, project::ProjectStage, quality::ContractReviewItem};

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DomainError {
    EmptyProjectCode,
    InvalidProjectCode(String),
    EmptyCustomerName,
    EmptyAuditActor,
    EmptyAuditReason,
    EmptyInstrumentCode,
    InvalidInstrumentCode(String),
    EmptyInstrumentManufacturer,
    EmptyInstrumentModel,
    EmptyInstrumentSerialNumber,
    EmptyCalibrationCertificate,
    EmptyCalibrationProvider,
    InvalidMetrologyDate {
        year: u16,
        month: u8,
        day: u8,
    },
    InvalidCalibrationPeriod,
    DuplicateInstrumentCode(String),
    UnknownInstrumentCode(String),
    EmptyInstrumentCommandMessage,
    UnsupportedInstrumentTransport(String),
    InstrumentCommandTargetMismatch {
        expected: String,
        actual: String,
    },
    EmptyTransportEndpointAddress,
    TransportAdapterMismatch {
        expected: String,
        actual: String,
    },
    InvalidInstrumentSafetyLimit {
        quantity: String,
        minimum: i64,
        maximum: i64,
    },
    InstrumentSetpointOutOfRange {
        quantity: String,
        value: i64,
        minimum: i64,
        maximum: i64,
    },
    EmptyUpdatePackageName,
    InvalidUpdatePackageName(String),
    EmptyUpdateSignature,
    EmptyRollbackReference,
    InvalidUpdateCompatibilityRange {
        minimum_version: String,
        maximum_version: String,
    },
    UnsignedUpdatePackage(String),
    IncompatibleUpdatePackage {
        package: String,
        minimum_version: String,
        maximum_version: Option<String>,
        actual_version: String,
    },
    OfflineUpdateInstallNotAllowed(String),
    UpdateDuringMeasurementBlocked(String),
    EmptyDatasetReference,
    InvalidDatasetReference(String),
    EmptyDatasetFileReference,
    EmptyDatasetChecksum,
    InvalidDatasetChecksum(String),
    DatasetRunMismatch {
        expected: String,
        actual: String,
    },
    ExecutionInstrumentNotPlanned(String),
    MeasurementRunMissingRawData,
    EmptySignalReference,
    InvalidSignalReference(String),
    EmptySignalUnit,
    InvalidSampleRateHz(u32),
    EmptySignalDataset,
    EmptySignalSamples(String),
    SignalSampleRateMismatch {
        left_hz: u32,
        right_hz: u32,
    },
    SignalSampleCountMismatch {
        left_count: usize,
        right_count: usize,
    },
    InvalidResamplingFactor(usize),
    EmptyProcessingNodeInputs,
    DuplicateProcessingNode(String),
    UnknownSignalReference(String),
    EmptyMeasurementRunReference,
    InvalidMeasurementRunReference(String),
    EmptyTestMethodReference,
    InvalidTestMethodReference(String),
    EmptyEquipmentSelection,
    EquipmentReadinessBlocked {
        blocking_issue_count: usize,
    },
    EmptyReportNumber,
    EmptyReportRevision,
    ReportTechnicalReviewRequired,
    ReportApprovalRequired,
    ReportMustBeIssuedBeforeExport,
    InvalidReportTransition {
        from: String,
        to: String,
    },
    EmptyRepositorySnapshotId,
    InvalidRepositorySnapshotId(String),
    EmptySyncConflictId,
    InvalidSyncConflictId(String),
    SyncConflictAlreadyResolved(String),
    UnknownSyncConflict(String),
    InvalidSyncConflictResolution {
        conflict: String,
        kind: String,
        resolution: String,
    },
    EmptySnapshotChecksum,
    InvalidRepositorySchemaVersion(u32),
    DuplicateRepositorySnapshot(String),
    MissingRepositorySnapshot(String),
    UnsignedRepositorySnapshot(String),
    IncompatibleRepositorySnapshot {
        domain: String,
        minimum_schema_version: u32,
        actual_schema_version: u32,
    },
    InvalidProjectTransition {
        from: ProjectStage,
        to: ProjectStage,
    },
    ChecklistProjectMismatch {
        project: ProjectCode,
        checklist_project: ProjectCode,
    },
    IncompleteContractReview {
        missing_items: Vec<ContractReviewItem>,
    },
}
